#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    OrgDefinedId?: string
    FirstName?: string
    MiddleName?: string
    LastName?: string
    ExternalEmail?: string
    UserName?: string
    RoleId?: integer
    IsActive?: boolean
    SendCreationEmail?: boolean
    Pronouns?: any
   
     
