#%RAML 1.0 DataType
type: object
properties:
  Identifier: string
  ProfileIdentifier: string
  DisplayName: string
  Username?: string | nil
  OrgDefinedId?: string | nil
  Email?: string | nil
  FirstName?: string | nil
  LastName?: string | nil
  RoleId?: integer | nil
  LastAccessed?: datetime | nil
  IsOnline: boolean
  ClasslistRoleDisplayName: string
  Pronouns?: string | nil
